#!/bin/bash

if [ 1 -ne "$#" ]; then
    echo "need an name for migration file"
    exit 1
fi

sudo docker run -v $PWD/migration:/migration --rm app_migration /bin/bash -c "./node_modules/.bin/sequelize migration:create --name $1"

sudo chmod -R a+wr $PWD/migration/migrations/

