version: '3'
services:
  git:
    image: 'gogs/gogs'
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - ./gogs/repos:/data/repos
      - ./gogs/logs:/data/logs
    links:
      - gogs_database:database  
  gogs_database:
    image: 'postgres'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_XLOGDIR=${POSTGRES_INITDB_XLOGDIR}
    ports:
      - "54320:5432"
    volumes:
      - ./postgres/logs:/var/log/postgres

