version: '3'
services:
  git:
    image: 'gogs/gogs'
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - ./gogs/repos:/data/repos
      - ./gogs/conf:/data/gogs/conf
      - ./gogs/logs:/data/logs
    links:
      - gogs_database:database
    depends_on:
      - gogs_database
  gogs_database:
    container_name: gogs_database
    image: 'postgres:9.6.5'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "54320:5432"
    volumes:
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/logs:/var/log/postgresql
